package com.haran.ecommerceapp.repositories;

import com.haran.ecommerceapp.models.Category;
import com.haran.ecommerceapp.models.Product;
import com.haran.ecommerceapp.repositories.Projection.ProductProjection;
import org.springframework.data.domain.Page;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.data.domain.Pageable;
import java.util.List;

public interface ProductRepository extends JpaRepository<Product,Long> {


    Product save(Product p);// the attributes that are automatically
    //  generated by DB will not be in the param, but will be there in
    // returned object

    Page<Product> findAll(Pageable pageable);

    Product findByIdIs(long id);

    void deleteById(long id);

    List<Product>  findByCategoryIs(Category category);

    List<Product> findAllByCategory_Title(String title);

    @Query("select p.title as title,p.id as id from Product p where p.category.title = :title")
    List<ProductProjection> findallTitleAndIdbyCategory(@Param("title") String cattitle);
}
